[package]
name = "clover_ui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.25.0"
rusttype = "0.9.3"
uuid = "1.4.1"
lazy_static = "1.4.0"
